/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "tribufu++/model/CodeChallengeMethod.h"

namespace tribufu {
namespace models {

namespace
{
using EnumUnderlyingType = utility::string_t;

CodeChallengeMethod::eCodeChallengeMethod toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("plain")))
        return CodeChallengeMethod::eCodeChallengeMethod::CodeChallengeMethod_PLAIN;
    if (val == utility::conversions::to_string_t(U("S256")))
        return CodeChallengeMethod::eCodeChallengeMethod::CodeChallengeMethod_S256;
    return {};
}

EnumUnderlyingType fromEnum(CodeChallengeMethod::eCodeChallengeMethod e)
{
    switch (e)
    {
    case CodeChallengeMethod::eCodeChallengeMethod::CodeChallengeMethod_PLAIN:
        return U("plain");
    case CodeChallengeMethod::eCodeChallengeMethod::CodeChallengeMethod_S256:
        return U("S256");
    default:
        break;
    }
    return {};
}
}

CodeChallengeMethod::CodeChallengeMethod()
{
}

CodeChallengeMethod::~CodeChallengeMethod()
{
}

void CodeChallengeMethod::validate()
{
    // TODO: implement validation
}

web::json::value CodeChallengeMethod::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool CodeChallengeMethod::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void CodeChallengeMethod::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool CodeChallengeMethod::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

CodeChallengeMethod::eCodeChallengeMethod CodeChallengeMethod::getValue() const
{
   return m_value;
}

void CodeChallengeMethod::setValue(CodeChallengeMethod::eCodeChallengeMethod const value)
{
   m_value = value;
}

}
}


