/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "tribufu++/model/GroupRank.h"

namespace tribufu
{
    namespace models
    {

        namespace
        {
            using EnumUnderlyingType = utility::string_t;

            GroupRank::eGroupRank toEnum(const EnumUnderlyingType &val)
            {
                if (val == utility::conversions::to_string_t(_XPLATSTR("member")))
                    return GroupRank::eGroupRank::GroupRank_MEMBER;
                if (val == utility::conversions::to_string_t(_XPLATSTR("leader")))
                    return GroupRank::eGroupRank::GroupRank_LEADER;
                if (val == utility::conversions::to_string_t(_XPLATSTR("owner")))
                    return GroupRank::eGroupRank::GroupRank_OWNER;
                return {};
            }

            EnumUnderlyingType fromEnum(GroupRank::eGroupRank e)
            {
                switch (e)
                {
                case GroupRank::eGroupRank::GroupRank_MEMBER:
                    return _XPLATSTR("member");
                case GroupRank::eGroupRank::GroupRank_LEADER:
                    return _XPLATSTR("leader");
                case GroupRank::eGroupRank::GroupRank_OWNER:
                    return _XPLATSTR("owner");
                default:
                    break;
                }
                return {};
            }
        }

        GroupRank::GroupRank()
        {
        }

        GroupRank::~GroupRank()
        {
        }

        void GroupRank::validate()
        {
            // TODO: implement validation
        }

        web::json::value GroupRank::toJson() const
        {
            auto val = fromEnum(m_value);
            return web::json::value(val);
        }

        bool GroupRank::fromJson(const web::json::value &val)
        {
            m_value = toEnum(val.as_string());
            return true;
        }

        void GroupRank::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t &prefix) const
        {
            utility::string_t namePrefix = prefix;
            if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
            {
                namePrefix.push_back(_XPLATSTR('.'));
            }

            auto e = fromEnum(m_value);
            multipart->add(ModelBase::toHttpContent(namePrefix, e));
        }

        bool GroupRank::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t &prefix)
        {
            bool ok = true;
            utility::string_t namePrefix = prefix;
            if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
            {
                namePrefix.push_back(_XPLATSTR('.'));
            }
            {
                EnumUnderlyingType e;
                ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
                if (ok)
                {
                    auto v = toEnum(e);
                    setValue(v);
                }
            }
            return ok;
        }

        GroupRank::eGroupRank GroupRank::getValue() const
        {
            return m_value;
        }

        void GroupRank::setValue(GroupRank::eGroupRank const value)
        {
            m_value = value;
        }

        GroupRank::GroupRank(utility::string_t str)
        {
            setValue(strToEnumMap[str]);
        }

    }
}
