/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "tribufu++/model/SearchType.h"

namespace tribufu
{
    namespace models
    {

        namespace
        {
            using EnumUnderlyingType = utility::string_t;

            SearchType::eSearchType toEnum(const EnumUnderlyingType &val)
            {
                if (val == utility::conversions::to_string_t(_XPLATSTR("user")))
                    return SearchType::eSearchType::SearchType_USER;
                if (val == utility::conversions::to_string_t(_XPLATSTR("group")))
                    return SearchType::eSearchType::SearchType_GROUP;
                if (val == utility::conversions::to_string_t(_XPLATSTR("server")))
                    return SearchType::eSearchType::SearchType_SERVER;
                if (val == utility::conversions::to_string_t(_XPLATSTR("cluster")))
                    return SearchType::eSearchType::SearchType_CLUSTER;
                return {};
            }

            EnumUnderlyingType fromEnum(SearchType::eSearchType e)
            {
                switch (e)
                {
                case SearchType::eSearchType::SearchType_USER:
                    return _XPLATSTR("user");
                case SearchType::eSearchType::SearchType_GROUP:
                    return _XPLATSTR("group");
                case SearchType::eSearchType::SearchType_SERVER:
                    return _XPLATSTR("server");
                case SearchType::eSearchType::SearchType_CLUSTER:
                    return _XPLATSTR("cluster");
                default:
                    break;
                }
                return {};
            }
        }

        SearchType::SearchType()
        {
        }

        SearchType::~SearchType()
        {
        }

        void SearchType::validate()
        {
            // TODO: implement validation
        }

        web::json::value SearchType::toJson() const
        {
            auto val = fromEnum(m_value);
            return web::json::value(val);
        }

        bool SearchType::fromJson(const web::json::value &val)
        {
            m_value = toEnum(val.as_string());
            return true;
        }

        void SearchType::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                                     const utility::string_t &prefix) const
        {
            utility::string_t namePrefix = prefix;
            if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
            {
                namePrefix.push_back(_XPLATSTR('.'));
            }

            auto e = fromEnum(m_value);
            multipart->add(ModelBase::toHttpContent(namePrefix, e));
        }

        bool SearchType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t &prefix)
        {
            bool ok = true;
            utility::string_t namePrefix = prefix;
            if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
            {
                namePrefix.push_back(_XPLATSTR('.'));
            }
            {
                EnumUnderlyingType e;
                ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
                if (ok)
                {
                    auto v = toEnum(e);
                    setValue(v);
                }
            }
            return ok;
        }

        SearchType::eSearchType SearchType::getValue() const
        {
            return m_value;
        }

        void SearchType::setValue(SearchType::eSearchType const value)
        {
            m_value = value;
        }

        SearchType::SearchType(utility::string_t str)
        {
            setValue(strToEnumMap[str]);
        }

    }
}
