/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "tribufu++/model/TokenHintType.h"

namespace tribufu
{
    namespace models
    {

        namespace
        {
            using EnumUnderlyingType = utility::string_t;

            TokenHintType::eTokenHintType toEnum(const EnumUnderlyingType &val)
            {
                if (val == utility::conversions::to_string_t(U("access_token")))
                    return TokenHintType::eTokenHintType::TokenHintType_ACCESS_TOKEN;
                if (val == utility::conversions::to_string_t(U("refresh_token")))
                    return TokenHintType::eTokenHintType::TokenHintType_REFRESH_TOKEN;
                return {};
            }

            EnumUnderlyingType fromEnum(TokenHintType::eTokenHintType e)
            {
                switch (e)
                {
                case TokenHintType::eTokenHintType::TokenHintType_ACCESS_TOKEN:
                    return U("access_token");
                case TokenHintType::eTokenHintType::TokenHintType_REFRESH_TOKEN:
                    return U("refresh_token");
                default:
                    break;
                }
                return {};
            }
        }

        TokenHintType::TokenHintType()
        {
        }

        TokenHintType::~TokenHintType()
        {
        }

        void TokenHintType::validate()
        {
            // TODO: implement validation
        }

        web::json::value TokenHintType::toJson() const
        {
            auto val = fromEnum(m_value);
            return web::json::value(val);
        }

        bool TokenHintType::fromJson(const web::json::value &val)
        {
            m_value = toEnum(val.as_string());
            return true;
        }

        void TokenHintType::toMultipart(std::shared_ptr<MultipartFormData> multipart,
                                        const utility::string_t &prefix) const
        {
            utility::string_t namePrefix = prefix;
            if (!namePrefix.empty() && namePrefix.back() != U('.'))
            {
                namePrefix.push_back(U('.'));
            }

            auto e = fromEnum(m_value);
            multipart->add(ModelBase::toHttpContent(namePrefix, e));
        }

        bool TokenHintType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t &prefix)
        {
            bool ok = true;
            utility::string_t namePrefix = prefix;
            if (!namePrefix.empty() && namePrefix.back() != U('.'))
            {
                namePrefix.push_back(U('.'));
            }
            {
                EnumUnderlyingType e;
                ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
                if (ok)
                {
                    auto v = toEnum(e);
                    setValue(v);
                }
            }
            return ok;
        }

        TokenHintType::eTokenHintType TokenHintType::getValue() const
        {
            return m_value;
        }

        void TokenHintType::setValue(TokenHintType::eTokenHintType const value)
        {
            m_value = value;
        }

    }
}
