/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GrantType.h
 *
 *
 */

#ifndef TRIBUFU_MODELS_GrantType_H_
#define TRIBUFU_MODELS_GrantType_H_

#include "tribufu++/ModelBase.h"

namespace tribufu
{
    namespace models
    {

        class GrantType : public ModelBase
        {
        public:
            GrantType();
            GrantType(utility::string_t str);
            operator utility::string_t() const
            {
                return enumToStrMap.at(getValue());
            }

            virtual ~GrantType();

            /////////////////////////////////////////////
            /// ModelBase overrides

            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

            enum class eGrantType
            {
                GrantType_AUTHORIZATION_CODE,
                GrantType_CLIENT_CREDENTIALS,
                GrantType_PASSWORD,
                GrantType_REFRESH_TOKEN,
            };

            eGrantType getValue() const;
            void setValue(eGrantType const value);

        protected:
            eGrantType m_value;
            std::map<eGrantType, utility::string_t> enumToStrMap = {
                {eGrantType::GrantType_AUTHORIZATION_CODE, "AUTHORIZATION_CODE"},
                {eGrantType::GrantType_CLIENT_CREDENTIALS, "CLIENT_CREDENTIALS"},
                {eGrantType::GrantType_PASSWORD, "PASSWORD"},
                {eGrantType::GrantType_REFRESH_TOKEN, "REFRESH_TOKEN"}};
            std::map<utility::string_t, eGrantType> strToEnumMap = {
                {"AUTHORIZATION_CODE", eGrantType::GrantType_AUTHORIZATION_CODE},
                {"CLIENT_CREDENTIALS", eGrantType::GrantType_CLIENT_CREDENTIALS},
                {"PASSWORD", eGrantType::GrantType_PASSWORD},
                {"REFRESH_TOKEN", eGrantType::GrantType_REFRESH_TOKEN}};
        };

    }
}

#endif /* TRIBUFU_MODELS_GrantType_H_ */
