/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LeaderboardOrder.h
 *
 *
 */

#ifndef TRIBUFU_MODELS_LeaderboardOrder_H_
#define TRIBUFU_MODELS_LeaderboardOrder_H_

#include "tribufu++/ModelBase.h"

namespace tribufu
{
    namespace models
    {

        class LeaderboardOrder : public ModelBase
        {
        public:
            LeaderboardOrder();
            LeaderboardOrder(utility::string_t str);
            operator utility::string_t() const
            {
                return enumToStrMap.at(getValue());
            }

            virtual ~LeaderboardOrder();

            /////////////////////////////////////////////
            /// ModelBase overrides

            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

            enum class eLeaderboardOrder
            {
                LeaderboardOrder_LEVEL,
                LeaderboardOrder_POINTS,
            };

            eLeaderboardOrder getValue() const;
            void setValue(eLeaderboardOrder const value);

        protected:
            eLeaderboardOrder m_value;
            std::map<eLeaderboardOrder, utility::string_t> enumToStrMap = {
                {eLeaderboardOrder::LeaderboardOrder_LEVEL, "LEVEL"},
                {eLeaderboardOrder::LeaderboardOrder_POINTS, "POINTS"}};
            std::map<utility::string_t, eLeaderboardOrder> strToEnumMap = {
                {"LEVEL", eLeaderboardOrder::LeaderboardOrder_LEVEL},
                {"POINTS", eLeaderboardOrder::LeaderboardOrder_POINTS}};
        };

    }
}

#endif /* TRIBUFU_MODELS_LeaderboardOrder_H_ */
