/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LoginRequest.h
 *
 *
 */

#ifndef TRIBUFU_MODELS_LoginRequest_H_
#define TRIBUFU_MODELS_LoginRequest_H_

#include "tribufu++/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace tribufu
{
    namespace models
    {

        class LoginRequest : public ModelBase
        {
        public:
            LoginRequest();
            virtual ~LoginRequest();

            /////////////////////////////////////////////
            /// ModelBase overrides

            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

            /////////////////////////////////////////////
            /// LoginRequest members

            utility::string_t getLogin() const;
            bool loginIsSet() const;
            void unsetLogin();
            void setLogin(const utility::string_t &value);

            utility::string_t getPassword() const;
            bool passwordIsSet() const;
            void unsetPassword();
            void setPassword(const utility::string_t &value);

        protected:
            utility::string_t m_Login;
            bool m_LoginIsSet;

            utility::string_t m_Password;
            bool m_PasswordIsSet;
        };

    }
}

#endif /* TRIBUFU_MODELS_LoginRequest_H_ */
