/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RegisterRequest.h
 *
 *
 */

#ifndef TRIBUFU_MODELS_RegisterRequest_H_
#define TRIBUFU_MODELS_RegisterRequest_H_

#include "tribufu++/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace tribufu
{
    namespace models
    {

        class RegisterRequest : public ModelBase
        {
        public:
            RegisterRequest();
            virtual ~RegisterRequest();

            /////////////////////////////////////////////
            /// ModelBase overrides

            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

            /////////////////////////////////////////////
            /// RegisterRequest members

            utility::string_t getUuid() const;
            bool uuidIsSet() const;
            void unsetUuid();
            void setUuid(const utility::string_t &value);

            utility::string_t getName() const;
            bool nameIsSet() const;
            void unsetName();
            void setName(const utility::string_t &value);

            utility::string_t getEmail() const;
            bool emailIsSet() const;
            void unsetEmail();
            void setEmail(const utility::string_t &value);

            utility::string_t getPassword() const;
            bool passwordIsSet() const;
            void unsetPassword();
            void setPassword(const utility::string_t &value);

        protected:
            utility::string_t m_Uuid;
            bool m_UuidIsSet;

            utility::string_t m_Name;
            bool m_NameIsSet;

            utility::string_t m_Email;
            bool m_EmailIsSet;

            utility::string_t m_Password;
            bool m_PasswordIsSet;
        };

    }
}

#endif /* TRIBUFU_MODELS_RegisterRequest_H_ */
