/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ResponseType.h
 *
 *
 */

#ifndef TRIBUFU_MODELS_ResponseType_H_
#define TRIBUFU_MODELS_ResponseType_H_

#include "tribufu++/ModelBase.h"

namespace tribufu
{
    namespace models
    {

        class ResponseType : public ModelBase
        {
        public:
            ResponseType();
            ResponseType(utility::string_t str);
            operator utility::string_t() const
            {
                return enumToStrMap.at(getValue());
            }

            virtual ~ResponseType();

            /////////////////////////////////////////////
            /// ModelBase overrides

            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

            enum class eResponseType
            {
                ResponseType_CODE,
                ResponseType_TOKEN,
            };

            eResponseType getValue() const;
            void setValue(eResponseType const value);

        protected:
            eResponseType m_value;
            std::map<eResponseType, utility::string_t> enumToStrMap = {{eResponseType::ResponseType_CODE, "CODE"},
                                                                       {eResponseType::ResponseType_TOKEN, "TOKEN"}};
            std::map<utility::string_t, eResponseType> strToEnumMap = {{"CODE", eResponseType::ResponseType_CODE},
                                                                       {"TOKEN", eResponseType::ResponseType_TOKEN}};
        };

    }
}

#endif /* TRIBUFU_MODELS_ResponseType_H_ */
