/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SearchType.h
 *
 * 
 */

#ifndef TRIBUFU_MODELS_SearchType_H_
#define TRIBUFU_MODELS_SearchType_H_


#include "tribufu++/ModelBase.h"


namespace tribufu {
namespace models {


class  SearchType
    : public ModelBase
{
public:
    SearchType();
    virtual ~SearchType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eSearchType
    {
        SearchType_USER,
        SearchType_GROUP,
        SearchType_SERVER,
        SearchType_CLUSTER,
    };

    eSearchType getValue() const;
    void setValue(eSearchType const value);

    protected:
        eSearchType m_value;
};

}
}

#endif /* TRIBUFU_MODELS_SearchType_H_ */
