/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TokenType.h
 *
 *
 */

#ifndef TRIBUFU_MODELS_TokenType_H_
#define TRIBUFU_MODELS_TokenType_H_

#include "tribufu++/ModelBase.h"

namespace tribufu
{
    namespace models
    {

        class TokenType : public ModelBase
        {
        public:
            TokenType();
            virtual ~TokenType();

            /////////////////////////////////////////////
            /// ModelBase overrides

            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

            enum class eTokenType
            {
                TokenType_BEARER,
            };

            eTokenType getValue() const;
            void setValue(eTokenType const value);

        protected:
            eTokenType m_value;
        };

    }
}

#endif /* TRIBUFU_MODELS_TokenType_H_ */
