/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TokenHintType.h
 *
 *
 */

#ifndef TRIBUFU_MODELS_TokenHintType_H_
#define TRIBUFU_MODELS_TokenHintType_H_

#include "tribufu++/ModelBase.h"

namespace tribufu
{
    namespace models
    {

        class TokenHintType : public ModelBase
        {
        public:
            TokenHintType();
            TokenHintType(utility::string_t str);
            operator utility::string_t() const
            {
                return enumToStrMap.at(getValue());
            }

            virtual ~TokenHintType();

            /////////////////////////////////////////////
            /// ModelBase overrides

            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

            enum class eTokenHintType
            {
                TokenHintType_ACCESS_TOKEN,
                TokenHintType_REFRESH_TOKEN,
            };

            eTokenHintType getValue() const;
            void setValue(eTokenHintType const value);

        protected:
            eTokenHintType m_value;
            std::map<eTokenHintType, utility::string_t> enumToStrMap = {
                {eTokenHintType::TokenHintType_ACCESS_TOKEN, "ACCESS_TOKEN"},
                {eTokenHintType::TokenHintType_REFRESH_TOKEN, "REFRESH_TOKEN"}};
            std::map<utility::string_t, eTokenHintType> strToEnumMap = {
                {"ACCESS_TOKEN", eTokenHintType::TokenHintType_ACCESS_TOKEN},
                {"REFRESH_TOKEN", eTokenHintType::TokenHintType_REFRESH_TOKEN}};
        };

    }
}

#endif /* TRIBUFU_MODELS_TokenHintType_H_ */
