/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdateProfile.h
 *
 * 
 */

#ifndef TRIBUFU_MODELS_UpdateProfile_H_
#define TRIBUFU_MODELS_UpdateProfile_H_


#include "tribufu++/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace tribufu {
namespace models {



class  UpdateProfile
    : public ModelBase
{
public:
    UpdateProfile();
    virtual ~UpdateProfile();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UpdateProfile members


    utility::string_t getDisplayName() const;
    bool displayNameIsSet() const;
    void unsetDisplay_name();
    void setDisplayName(const utility::string_t& value);

    utility::string_t getBiography() const;
    bool biographyIsSet() const;
    void unsetBiography();
    void setBiography(const utility::string_t& value);


protected:
    utility::string_t m_Display_name;
    bool m_Display_nameIsSet;

    utility::string_t m_Biography;
    bool m_BiographyIsSet;

};


}
}

#endif /* TRIBUFU_MODELS_UpdateProfile_H_ */
