/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnyType.h
 *
 * This is the implementation of an any JSON type.
 */

#ifndef TRIBUFU_MODELS_AnyType_H_
#define TRIBUFU_MODELS_AnyType_H_

#include "tribufu++/Object.h"

#include <cpprest/details/basic_types.h>
#include <cpprest/json.h>

namespace tribufu
{
    namespace models
    {

        class AnyType : public Object
        {
        public:
            AnyType();
            virtual ~AnyType();

            /////////////////////////////////////////////
            /// ModelBase overrides
            void validate() override;

            web::json::value toJson() const override;
            bool fromJson(const web::json::value &json) override;

            void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                             const utility::string_t &namePrefix) const override;
            bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                               const utility::string_t &namePrefix) override;

        private:
            web::json::value m_value;
        };

    }
}

#endif /* TRIBUFU_MODELS_AnyType_H_ */
