/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IHttpBody.h
 *
 * This is the interface for contents that can be sent to a remote HTTP server.
 */

#ifndef TRIBUFU_MODELS_IHttpBody_H_
#define TRIBUFU_MODELS_IHttpBody_H_

#include <iostream>

namespace tribufu
{
    namespace models
    {

        class IHttpBody
        {
        public:
            virtual ~IHttpBody()
            {
            }

            virtual void writeTo(std::ostream &stream) = 0;
        };

    }
}

#endif /* TRIBUFU_MODELS_IHttpBody_H_ */
