/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.12.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * JsonBody.h
 *
 * This is a JSON http body which can be submitted via http
 */

#ifndef TRIBUFU_MODELS_JsonBody_H_
#define TRIBUFU_MODELS_JsonBody_H_

#include "tribufu++/IHttpBody.h"

#include <cpprest/json.h>

namespace tribufu
{
    namespace models
    {

        class JsonBody : public IHttpBody
        {
        public:
            JsonBody(const web::json::value &value);
            virtual ~JsonBody();

            void writeTo(std::ostream &target) override;

        protected:
            web::json::value m_Json;
        };

    }
}

#endif /* TRIBUFU_MODELS_JsonBody_H_ */
