/**
 * Tribufu API
 * REST API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "tribufu++/ApiException.h"

namespace tribufu
{
    namespace api
    {

        ApiException::ApiException(int errorCode, const utility::string_t &message,
                                   std::shared_ptr<std::istream> content /*= nullptr*/)
            : web::http::http_exception(errorCode, message), m_Content(content)
        {
        }
        ApiException::ApiException(int errorCode, const utility::string_t &message,
                                   std::map<utility::string_t, utility::string_t> &headers,
                                   std::shared_ptr<std::istream> content /*= nullptr*/)
            : web::http::http_exception(errorCode, message), m_Content(content), m_Headers(headers)
        {
        }

        ApiException::~ApiException()
        {
        }

        std::shared_ptr<std::istream> ApiException::getContent() const
        {
            return m_Content;
        }

        std::map<utility::string_t, utility::string_t> &ApiException::getHeaders()
        {
            return m_Headers;
        }

    }
}
